version: "3.8"
services:
  web:
    build: .
    container_name: php-app
    # Bind host port 8080 to container port 80 for web access
    ports:
      - "8080:80"
    # Mount project root so changes are reflected immediately
    volumes:
      - ../:/var/www/html
    depends_on:
      - db
    environment:
      # Not strictly necessary, but can be used for config
      DB_HOST: db
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydb

  db:
    image: postgres:13
    container_name: pgdb
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
